#!/usr/bin/env python2
# -*- coding: utf-8 -*-
# Filename: duty_time_analysis.R
#
# Description: analyze result generated by duty_time_group in order to give a method to classify servers.
#
# Copyright (c) 2017, Yusheng Yi <yiyusheng.hust@gmail.com>
#
# Version 1.0
#
# Initial created: 2017-04-12 20:44:40
#
# Last   modified: 2017-04-12 20:44:42
#
#
#
rm(list = ls());source('~/rhead')
load(file.path(dir_data,'duty_time_group.Rda'))

###### A1.merge busy in one ######
dts <- duty_time_svrid
dts$count_busy <- with(dts,count2 + count3 + count4)
dts$sum_busy <- with(dts,sum2 + sum3 + sum4)
dts <- dts[,c('svrid','util_count','util_sum','count1','count_busy','sum1','sum_busy')]
names(dts) <- c('svrid','util_count','util_sum','count_idle','count_busy','sum_idle','sum_busy')
dts$util_rate <- with(dts,roundX(util_sum/util_count))
dts$idle_rate <- with(dts,roundX(sum_idle/count_idle))
dts$busy_rate <- with(dts,roundX(sum_busy/count_busy))
dts$idle_total_rate <- with(dts,roundX(sum_idle/util_count))
dts$busy_total_rate <- with(dts,roundX(sum_busy/util_count))
dts <- replace_value(dts)

# P1.relationship between two factors
ggplot(dts,aes(x = util_count,y = util_sum)) + geom_point(alpha = 0.01) + geom_abline(slope = 1,intercept = 0)
ggplot(dts,aes(x = util_rate,y = busy_rate)) + geom_point(alpha = 0.01) + geom_abline(slope = 1,intercept = 0)
ggplot(dts,aes(x = idle_rate,y = busy_rate)) + geom_point(alpha = 0.01)

# P2.distribution of different rate
p1 <- ggplot(dts,aes(x = log2(util_rate))) + geom_histogram(binwidth = 0.01)
p2 <- ggplot(dts,aes(x = log2(idle_rate))) + geom_histogram(binwidth = 0.01)
p3 <- ggplot(dts,aes(x = log2(busy_rate))) + geom_histogram(binwidth = 0.01)
p4 <- ggplot(dts,aes(x = log2(idle_total_rate))) + geom_histogram(binwidth = 0.01)
p5 <- ggplot(dts,aes(x = log2(busy_total_rate))) + geom_histogram(binwidth = 0.01)
multiplot(p1,p2,p3,p4,p5,cols = 1)

# P3.quantile plot of different rate
quan_rate <- data.frame(apply(dts[,grepl('rate',names(dts))],2,function(x)quantileX(log2(x[x!= 0]))))
quan_rate$quan <- 0:100
qr_dcast <- melt(quan_rate,id.vars = 'quan')
ggplot(qr_dcast,aes(x = quan,y = value,color = variable)) + geom_line()

# P4.fraction of total duty time with busy workload
dts_f1 <- dts[,c('svrid','util_rate','busy_total_rate')]
dts_f1$frac_busy <- with(dts_f1,busy_total_rate/util_rate)
dts_f1 <- replace_value(dts_f1)
ggplot(dts_f1) + 
  geom_boxplot(aes(x = factor(round(util_rate,1)),y = frac_busy),outlier.shape = NA) + 
  geom_jitter(aes(x = factor(round(util_rate,1)),y = frac_busy),alpha = 0.01, width = 0.2)

# C1. util_rate based classification
dts_classify_util_rate <- dts[,c('svrid','util_rate','idle_rate','busy_rate')]
dts_classify_util_rate$util_rate_level <- log2(dts_classify_util_rate$util_rate)
dts_classify_util_rate[,2:5] <- replace_value(dts_classify_util_rate[,2:5],v1 = Inf,v2 = -14)
cut_util_rate <- c(seq(-14,-2,2),1)
# cut_util_rate <- c(seq(-16,-4,4),1)
dts_classify_util_rate$cut_ur <- cut(dts_classify_util_rate$util_rate_level,cut_util_rate,cut_util_rate[-length(cut_util_rate)],right = F)
save(dts_classify_util_rate,file = file.path(dir_data,'dts_classify_util_rate.Rda'))
